import { useState } from 'react'
import { Download } from 'lucide-react'
import { downloadRecoveryExport, getRecoveryReminderDay, isRecoveryReminderDue, markRecoveryExportDownloaded, setRecoveryReminderDay } from './recoveryExport'

export function RecoveryExportSection() {
  const [day, setDay] = useState(getRecoveryReminderDay); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [due, setDue] = useState(() => isRecoveryReminderDue())
  async function download() { setBusy(true); setError(null); try { await downloadRecoveryExport(); markRecoveryExportDownloaded(); setDue(false) } catch { setError('We couldn’t create a complete recovery export. Nothing was downloaded.') } finally { setBusy(false) } }
  return <section className="security-section" aria-labelledby="recovery-export-title"><div className="security-section-heading"><div><h2 id="recovery-export-title">Data & recovery</h2><p>Download a complete JSON recovery export of your current records and immutable history. Store it encrypted in a private location you control.</p></div><button className="button button-primary" type="button" disabled={busy} onClick={() => void download()}><Download size={17} />{busy ? 'Preparing export…' : 'Download recovery export'}</button></div>{due && <p className="security-note" role="status">Your monthly recovery export is due.</p>}{error && <p className="form-message error" role="alert">{error}</p>}<label className="recovery-reminder">Monthly reminder day<select aria-label="Monthly recovery export reminder day" value={day} onChange={(event) => { const next = Number(event.target.value); setDay(next); setRecoveryReminderDay(next); setDue(isRecoveryReminderDue(next)) }}>{Array.from({ length: 28 }, (_, index) => index + 1).map((value) => <option key={value} value={value}>{value}</option>)}</select><span>When you open this page on or after this day, make a fresh recovery export. This is a reminder only: no file is created, uploaded, emailed, or retained automatically.</span></label></section>
}
