import { useEffect, useRef, useState } from 'react'
import type { FormEvent } from 'react'
import { useMutation, useQueryClient } from '@tanstack/react-query'
import { X } from 'lucide-react'
import { Button } from '@/components/ui/Button'
import { positionIntentSchema } from '@/lib/validation'
import type { AccountResponse, OpenPositionResponse, PositionIntent } from '@/lib/validation'
import { supabase } from '@/lib/supabase'

const assetTypes = ['stock', 'etf', 'mutual_fund', 'bond', 'crypto', 'cash_equivalent', 'other'] as const
const eventTypes = ['manual_adjustment', 'buy', 'sell', 'correction'] as const
const nowLocal = () => new Date().toISOString().slice(0, 16)
const asUtc = (value: string) => new Date(value).toISOString()

function Dialog({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) {
  const closeRef = useRef<HTMLButtonElement>(null)
  useEffect(() => { closeRef.current?.focus(); const escape = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose() }; window.addEventListener('keydown', escape); return () => window.removeEventListener('keydown', escape) }, [onClose])
  return <div className="dialog-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose() }}><section className="dialog" role="dialog" aria-modal="true" aria-labelledby="position-dialog-title"><button ref={closeRef} className="dialog-close" type="button" onClick={onClose} aria-label="Close position form"><X size={18} /></button><h2 id="position-dialog-title">{title}</h2>{children}</section></div>
}

function invalidate(client: ReturnType<typeof useQueryClient>, portfolioId: string) { return Promise.all([client.invalidateQueries({ queryKey: ['accounts', portfolioId] }), client.invalidateQueries({ queryKey: ['open-positions', portfolioId] })]) }

export function PositionDialog({ portfolioId, accounts, position, onClose }: { portfolioId: string; accounts: AccountResponse[]; position?: OpenPositionResponse; onClose: () => void }) {
  const client = useQueryClient(); const requestId = useRef(crypto.randomUUID()); const [eventType, setEventType] = useState<(typeof eventTypes)[number]>('manual_adjustment'); const [confirmClose, setConfirmClose] = useState(false)
  const [form, setForm] = useState({ accountId: position?.account_id ?? (accounts.length === 1 ? accounts[0]!.id : ''), symbol: position?.symbol ?? '', securityName: position?.security_name ?? '', assetType: position?.asset_type ?? 'etf', quantity: position?.quantity ?? '', averageCost: position?.average_cost ?? '', occurredAt: nowLocal(), notes: '' })
  const [error, setError] = useState<string | null>(null)
  const mutation = useMutation({ mutationFn: async (intent: PositionIntent) => {
    const result = position ? await supabase.rpc('edit_position', { p_position_id: position.id, p_event_type: confirmClose ? 'close' : eventType, p_new_account_id: intent.accountId, p_new_symbol: position.symbol, p_new_security_name: position.security_name, p_new_asset_type: position.asset_type, p_new_quantity: confirmClose ? null : intent.quantity, p_new_average_cost: confirmClose ? null : intent.averageCost, p_split_numerator: null, p_split_denominator: null, p_dividend_amount: null, p_occurred_at: intent.occurredAt, p_notes: intent.notes, p_request_id: requestId.current }) : await supabase.rpc('create_position', { p_portfolio_id: portfolioId, p_account_id: intent.accountId, p_symbol: intent.symbol, p_security_name: intent.securityName, p_asset_type: intent.assetType, p_quantity: intent.quantity, p_average_cost: intent.averageCost, p_occurred_at: intent.occurredAt, p_notes: intent.notes, p_request_id: requestId.current })
    if (result.error) throw result.error
  }, onSuccess: async () => { await invalidate(client, portfolioId); onClose() }, onError: () => setError('We couldn’t save this position. Please try again.') })
  function submit(event: FormEvent) { event.preventDefault(); let occurredAt: string; try { occurredAt = asUtc(form.occurredAt) } catch { setError('Check the position details and try again.'); return }; const parsed = position ? positionIntentSchema.safeParse({ ...form, symbol: position.symbol, securityName: position.security_name, assetType: position.asset_type, occurredAt, notes: form.notes || null }) : positionIntentSchema.safeParse({ ...form, occurredAt, notes: form.notes || null }); if (!parsed.success || !accounts.some(({ id }) => id === form.accountId)) { setError('Check the position details and try again.'); return }; setError(null); mutation.mutate(parsed.data) }
  const changing = (key: keyof typeof form, value: string) => setForm({ ...form, [key]: value })
  return <Dialog title={position ? (confirmClose ? 'Close position' : 'Edit position') : 'Add position'} onClose={onClose}><form className="account-form" onSubmit={submit} noValidate aria-describedby={error ? 'position-error' : undefined}>{position && <label>Update reason<select value={eventType} onChange={(event) => setEventType(event.target.value as typeof eventType)}><option value="manual_adjustment">Manual adjustment</option><option value="buy">Buy</option><option value="sell">Sell</option><option value="correction">Correction</option></select></label>}<label>Account<select value={form.accountId} onChange={(event) => changing('accountId', event.target.value)}><option value="">Choose an account</option>{accounts.map((account) => <option value={account.id} key={account.id}>{account.name}</option>)}</select></label>{!position && <><label>Ticker<input value={form.symbol} onChange={(event) => changing('symbol', event.target.value)} /></label><label>Security name<input value={form.securityName} onChange={(event) => changing('securityName', event.target.value)} /></label><label>Asset type<select value={form.assetType} onChange={(event) => changing('assetType', event.target.value)}>{assetTypes.map((type) => <option value={type} key={type}>{type.replace('_', ' ')}</option>)}</select></label></>} {!confirmClose && <><label>Shares<input inputMode="decimal" value={form.quantity} onChange={(event) => changing('quantity', event.target.value)} /></label><label>Average cost<input inputMode="decimal" value={form.averageCost} onChange={(event) => changing('averageCost', event.target.value)} /></label></>}<label>Effective date and time<input type="datetime-local" value={form.occurredAt} onChange={(event) => changing('occurredAt', event.target.value)} /></label><label>Notes <span>(optional)</span><textarea value={form.notes} maxLength={500} onChange={(event) => changing('notes', event.target.value)} /></label>{confirmClose && <p className="confirmation-copy">This removes the holding from the current view. Historical records are preserved.</p>}{error && <p id="position-error" className="form-error" role="alert">{error}</p>}<div className="dialog-actions">{position && !confirmClose && <Button className="button-text" type="button" onClick={() => setConfirmClose(true)}>Close position</Button>}<Button className="button-secondary" type="button" onClick={onClose}>Cancel</Button><Button className="button-primary" disabled={mutation.isPending}>{mutation.isPending ? 'Saving…' : confirmClose ? 'Close position' : 'Save position'}</Button></div></form></Dialog>
}
