import { useEffect, useRef, useState } from 'react'
import type { FormEvent } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Plus, X } from 'lucide-react'
import { Button } from '@/components/ui/Button'
import { EmptyState, ErrorState, LoadingState } from '@/components/ui/States'
import { accountResponseSchema, liabilityInputSchema, liabilityResponseSchema, manualAssetInputSchema, manualAssetResponseSchema, portfolioResponseSchema } from '@/lib/validation'
import type { LiabilityInput, LiabilityResponse, ManualAssetInput, ManualAssetResponse } from '@/lib/validation'
import { supabase } from '@/lib/supabase'
import { formatUsd } from '@/features/portfolio/prices'

type Kind = 'asset' | 'liability'
const categories = { asset: ['cash', 'savings', 'real_estate', 'vehicle', 'business_equity', 'collectible', 'other'], liability: ['mortgage', 'vehicle_loan', 'student_loan', 'credit_balance', 'personal_loan', 'other'] } as const
const title = { asset: 'Assets', liability: 'Liabilities' } as const
const query = async (kind: Kind) => { const { data: portfolioData, error: portfolioError } = await supabase.from('portfolios').select('id, name').eq('is_primary', true).limit(1); if (portfolioError) throw portfolioError; const portfolio = portfolioResponseSchema.parse(portfolioData)[0]; if (!portfolio) throw new Error('Portfolio unavailable'); const [{ data: accountsData, error: accountsError }, { data: itemsData, error: itemsError }] = await Promise.all([supabase.from('accounts').select('id, portfolio_id, name, institution_name, account_type, include_in_net_worth').eq('portfolio_id', portfolio.id).order('created_at'), supabase.from(kind === 'asset' ? 'manual_assets' : 'liabilities').select('*').eq('portfolio_id', portfolio.id).order('created_at')]); if (accountsError || itemsError) throw accountsError ?? itemsError; return { portfolio, accounts: accountResponseSchema.parse(accountsData), items: kind === 'asset' ? manualAssetResponseSchema.parse(itemsData) : liabilityResponseSchema.parse(itemsData) } }
const localNow = () => new Date().toISOString().slice(0, 16)

function ValueItemForm({ kind, portfolioId, accounts, item, onClose }: { kind: Kind; portfolioId: string; accounts: Awaited<ReturnType<typeof query>>['accounts']; item?: ManualAssetResponse | LiabilityResponse; onClose: () => void }) {
  const client = useQueryClient(); const value = item && ('current_value' in item ? item.current_value : item.outstanding_balance)
  const closeRef = useRef<HTMLButtonElement>(null); useEffect(() => { closeRef.current?.focus(); const escape = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose() }; window.addEventListener('keydown', escape); return () => window.removeEventListener('keydown', escape) }, [onClose])
  const [form, setForm] = useState({ accountId: item?.account_id ?? '', name: item?.name ?? '', category: item?.category ?? categories[kind][0], value: value ?? '', includeInNetWorth: item?.include_in_net_worth ?? true, notes: item?.notes ?? '', asOf: item ? new Date(('value_as_of' in item ? item.value_as_of : item.balance_as_of) ?? new Date().toISOString()).toISOString().slice(0, 16) : localNow() }); const [error, setError] = useState<string | null>(null)
  const mutation = useMutation({ mutationFn: async (input: ManualAssetInput | LiabilityInput) => { let result; if (kind === 'asset') { const asset = input as ManualAssetInput; const payload = { portfolio_id: portfolioId, account_id: asset.accountId, name: asset.name, category: asset.category, current_value: asset.value, include_in_net_worth: asset.includeInNetWorth, notes: asset.notes, value_as_of: asset.asOf }; result = item ? await supabase.from('manual_assets').update(payload).eq('id', item.id) : await supabase.from('manual_assets').insert(payload) } else { const liability = input as LiabilityInput; const payload = { portfolio_id: portfolioId, account_id: liability.accountId, name: liability.name, category: liability.category, outstanding_balance: liability.value, include_in_net_worth: liability.includeInNetWorth, notes: liability.notes, balance_as_of: liability.asOf }; result = item ? await supabase.from('liabilities').update(payload).eq('id', item.id) : await supabase.from('liabilities').insert(payload) }; if (result.error) throw result.error }, onSuccess: async () => { await client.invalidateQueries({ queryKey: [kind] }); onClose() }, onError: () => setError(`We couldn’t save this ${kind}. Please try again.`) })
  function submit(event: FormEvent) { event.preventDefault(); let asOf: string; try { asOf = new Date(form.asOf).toISOString() } catch { setError(`Check the ${kind} details and try again.`); return }; const candidate = { ...form, accountId: form.accountId || null, notes: form.notes || null, asOf }; const parsed = (kind === 'asset' ? manualAssetInputSchema : liabilityInputSchema).safeParse(candidate); if (!parsed.success || (form.accountId && !accounts.some(({ id }) => id === form.accountId))) { setError(`Check the ${kind} details and try again.`); return }; mutation.mutate(parsed.data) }
  return <div className="dialog-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose() }}><section className="dialog" role="dialog" aria-modal="true" aria-labelledby="value-item-title"><button ref={closeRef} className="dialog-close" type="button" onClick={onClose} aria-label={`Close ${kind} form`}><X size={18} /></button><h2 id="value-item-title">{item ? `Edit ${kind}` : `Add ${kind}`}</h2><form className="account-form" onSubmit={submit} noValidate><label>Name<input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>Account <span>(optional)</span><select value={form.accountId} onChange={(event) => setForm({ ...form, accountId: event.target.value })}><option value="">No account association</option>{accounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select></label><label>Category<select value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value as typeof form.category })}>{categories[kind].map((category) => <option key={category} value={category}>{category.replace('_', ' ')}</option>)}</select></label><label>{kind === 'asset' ? 'Current value' : 'Outstanding balance'}<input inputMode="decimal" value={form.value} onChange={(event) => setForm({ ...form, value: event.target.value })} /></label><label>As of<input type="datetime-local" value={form.asOf} onChange={(event) => setForm({ ...form, asOf: event.target.value })} /></label><label className="checkbox-row"><input type="checkbox" checked={form.includeInNetWorth} onChange={(event) => setForm({ ...form, includeInNetWorth: event.target.checked })} /> Include in net worth</label><label>Notes <span>(optional)</span><textarea maxLength={500} value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} /></label>{error && <p className="form-error" role="alert">{error}</p>}<div className="dialog-actions"><Button className="button-secondary" type="button" onClick={onClose}>Cancel</Button><Button className="button-primary" disabled={mutation.isPending}>{mutation.isPending ? 'Saving…' : `Save ${kind}`}</Button></div></form></section></div>
}

export function ValueItemsPage({ kind }: { kind: Kind }) {
  const data = useQuery({ queryKey: [kind], queryFn: () => query(kind) }); const [editing, setEditing] = useState<ManualAssetResponse | LiabilityResponse | null | undefined>()
  if (data.isPending) return <LoadingState>Loading your {title[kind].toLowerCase()}…</LoadingState>
  if (data.isError || !data.data) return <ErrorState onRetry={() => void data.refetch()} />
  const { portfolio, accounts, items } = data.data; const rows = items as (ManualAssetResponse | LiabilityResponse)[]
  return <section><header className="page-header"><div><h1>{title[kind]}, kept current.</h1><p>Current-state records, retained separately from position history.</p></div><Button className="button-primary" onClick={() => setEditing(null)}><Plus size={16} /> Add {kind}</Button></header>{data.isFetching && <p className="refetch-copy" role="status">Refreshing {title[kind].toLowerCase()}…</p>}{rows.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>Name</th><th>Account</th><th>Category</th><th>{kind === 'asset' ? 'Value' : 'Balance'}</th><th>Included</th><th>As of</th><th><span className="sr-only">Action</span></th></tr></thead><tbody>{rows.map((item) => { const amount = ('current_value' in item ? item.current_value : item.outstanding_balance) ?? '0'; const timestamp = ('value_as_of' in item ? item.value_as_of : item.balance_as_of) ?? ''; return <tr key={item.id}><td><strong>{item.name}</strong>{item.notes && <small>{item.notes}</small>}</td><td>{accounts.find(({ id }) => id === item.account_id)?.name ?? 'No account'}</td><td>{item.category.replace('_', ' ')}</td><td>{formatUsd(amount)}</td><td>{item.include_in_net_worth ? 'Included' : 'Excluded'}</td><td>{new Date(timestamp).toLocaleString()}</td><td><Button className="button-text" onClick={() => setEditing(item)}>Edit</Button></td></tr> })}</tbody></table></div> : <EmptyState>Add the first {kind} you want reflected here.</EmptyState>}{editing !== undefined && <ValueItemForm kind={kind} portfolioId={portfolio.id} accounts={accounts} item={editing ?? undefined} onClose={() => setEditing(undefined)} />}</section>
}
